//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProje.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogDiziEntities : DbContext
    {
        public BlogDiziEntities()
            : base("name=BlogDiziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Blog> TBL_Blog { get; set; }
        public virtual DbSet<TBL_Hakkimizda> TBL_Hakkimizda { get; set; }
        public virtual DbSet<TBL_Iletisim> TBL_Iletisim { get; set; }
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_Tur> TBL_Tur { get; set; }
        public virtual DbSet<TBL_Yorum> TBL_Yorum { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Roller> TBL_Roller { get; set; }
        public virtual DbSet<TBL_City> TBL_City { get; set; }
        public virtual DbSet<TBL_Country> TBL_Country { get; set; }
        public virtual DbSet<TBL_State> TBL_State { get; set; }
    }
}
